name: Build youtube-dl image

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
    - cron: '0 12 * * 2,5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --rm --no-cache --file Dockerfile --tag docker-youtube-dl:$(date +%s)
